version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: roster-manager-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roster_manager_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  # Uncomment if you want a GUI for database management
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: roster-manager-pgadmin
  #   restart: unless-stopped
  #   ports:
  #     - '5050:80'
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@roster-manager.local
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
    driver: local
